apiVersion: apps/v1
kind: Deployment
metadata:
  name: paid-media-userlist-deployment
  labels:
    app: paid-media-userlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paid-media-userlist
  template:
    metadata:
      labels:
        app: paid-media-userlist
    spec:
      containers:
      - name: paid-media-userlist
        image: paid-media-userlist
        env:
          - name: MARIADB_USR
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: MARIADB_USR
          - name: MARIADB_PSW
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: MARIADB_PSW
      imagePullSecrets:
        - name: gh-docker-creds